# Generated by Django 4.2 on 2024-05-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocs.medicalrecord'),
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
