# Generated by Django 4.2 on 2024-06-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_practitioner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practitioner',
            name='email',
        ),
    ]
