# Generated by Django 4.2 on 2024-06-12 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('booked', 'Booked'), ('pending', 'Pending'), ('arrived', 'Arrived'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('noshow', 'No Show'), ('entered_in_error', 'Entered in Error'), ('waitlist', 'Waitlist')], default='booked', max_length=20)),
                ('appointmentType', models.CharField(choices=[('routine', 'Routine'), ('walkin', 'Walkin'), ('checkup', 'Checkup'), ('followup', 'Followup'), ('emergency', 'Emergency')], max_length=20)),
                ('start', models.DateTimeField()),
                ('minutesDuration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('requested_period_start', models.DateTimeField(blank=True, null=True)),
                ('requested_period_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('patient_instruction', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.practitioner')),
            ],
        ),
    ]
