# Generated by Django 4.2 on 2024-05-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocs', '0001_initial'),
        ('account', '0002_alter_patient_medical_record_delete_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('insurance', models.CharField(max_length=20)),
                ('patient_paid', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('cancelled', 'cancelled'), ('draft', 'draft'), ('entered-in-error', 'entered-in-error')], max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.department')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocs.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
            ],
        ),
    ]
