# Generated by Django 4.2 on 2024-06-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedure', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('complete', 'complete'), ('active', 'active'), ('cancelled', 'cancelled'), ('draft', 'draft'), ('entered-in-error', 'entered-in-error')], max_length=20)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim', to='account.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargeItem', to='acceptance.claim')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chargeItems', to='account.patient')),
                ('procedure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='chargeItem', to='procedure.procedure')),
            ],
        ),
    ]
