# Generated by Django 4.2 on 2024-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('insurance', models.CharField(max_length=20)),
                ('patient_paid', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('cancelled', 'cancelled'), ('draft', 'draft'), ('entered-in-error', 'entered-in-error')], max_length=20)),
            ],
        ),
    ]
