# Generated by Django 4.2 on 2024-05-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_annual_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual',
            name='reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
