# Generated by Django 4.2 on 2024-06-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_code', models.CharField(max_length=30)),
                ('procedure_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
