# Generated by Django 4.2 on 2024-06-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedure', '0001_initial'),
        ('acceptance', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('diagnostic_results', models.TextField(blank=True)),
                ('surgical_request_record', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_result', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('charge_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acceptance.chargeitem')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ocs.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.practitioner')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedure.procedure')),
            ],
        ),
    ]
